# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_result',
            name='headline',
            field=models.TextField(primary_key=True),
        ),
    ]
