# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20170816_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_result',
            name='headline',
            field=models.TextField(),
        ),
    ]
