# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20170816_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='djangoFNC',
            fields=[
                ('headlineID', models.IntegerField(primary_key=True, serialize=False)),
                ('bodyID', models.IntegerField()),
                ('stance1', models.FloatField()),
                ('stance2', models.FloatField()),
                ('stance3', models.FloatField()),
                ('stance4', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Train_Result',
        ),
    ]
