# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB',
            fields=[
                ('headlineID', models.IntegerField(primary_key=True, serialize=False)),
                ('bodyID', models.IntegerField()),
                ('stance1', models.FloatField()),
                ('stance2', models.FloatField()),
                ('stance3', models.FloatField()),
                ('stance4', models.FloatField()),
            ],
        ),
    ]
